POST http://localhost:5248
Content-Type: application/json

{
    "device": "Смартфон",
    "problemType": "Экран",
    "problemDesc": "Экран не реагирует на прикосновения",
    "client": "Петр Петров",
    "Status": "в_работе"
}




###
GET http://localhost:5248

####
POST http://localhost:5248
Content-Type: application/json

{
    "device": "Смартфон",
    "problemType": "Экран",
    "problemDesc": "Экран не реагирует на прикосновения",
    "client": "Петр Петров"
}
